image: python:3.12

stages:
  - lint
  - validate

before_script:
  - pip install --upgrade pip
  - pip install poetry
  - poetry install --only main

lint:
  stage: lint
  script:
    - poetry run reporting lint

validate:
  stage: validate
  script:
    - poetry run reporting validate
